[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/whatsapp"
  to = "/.netlify/functions/whatsapp"
  status = 200

[build.environment]
  NODE_VERSION = "18"